add:
	vagrant box add jasonc/centos7

init:
	vagrant init jasonc/centos7

up:
	vagrant up

ssh:
	vagrant ssh

status:
	vagrant status

halt:
	vagrant halt

reload:
	vagrant reload

destroy:
	vagrant destroy -f
